[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API proxy (optional - you can also call EC2 directly)
[[redirects]]
  from = "/api/*"
  to = "https://thhepaak.onrender.com/api/:splat"
  status = 200
  force = true

# WebSocket proxy (if needed)
[[redirects]]
  from = "/ws"
  to = "https://thhepaak.onrender.com/ws"
  status = 200
  force = true 